### PR TITLE
New band added

### PR DESCRIPTION
**Pull request by asficas**
New Feature added to support the Band for 5362 MHz, 5399 MHz, 5436 MHz, 5473 MHz, 5510 MHz, 5547 MHz, 5584 MHz and 5621 MHz. Manual search and Auto search modes working, scanner also.
Adapted the OLED screens slightly to accommodate 8 new channels. 

The User can enable the feature by uncommenting #define USE_LBAND in settings.h

### CODE REVIEW

**Comment by sheaivey** [comment]
This is looking good. I like the fact that you created a feature toggle for the L band. Which to my knowledge is illegal in the US still.

Before I accept this PR could you default to the L band being disabled? My concern is people will not bat an eye about when they go to using those channels.

-Shea

**Comment by ps915** [comment]
Hi Shea,

You don't have to worry about if, its illegal or not because you are just receiving the signal on those bands/channels. Only the VTX who sends the signal has to worry about it.

So it would be fine to just add the new Bands.

By the way, here you can see which channels are allowed in germany. The original raceband is just allowed to use on CH3-Ch6 ;-)
http://blog.seidel-philipp.de/wp-content/uploads/2016/06/fpv_frequenzen_5_8Ghz.png

- Phil

**Comment by sheaivey** [comment]
You are correct there is nothing wrong with receiving those signals however if we make it too easy for people to unknowingly break their local laws the potential for them to do so skyrockets.

This new L band is so far outside the amateur radio spectrum here in the US there should be some word of warning or user action required (Such as enabling the L band feature toggle). 

Just because a new VTX comes out with a new band does not mean it can be legally used nor should we promote its use. Especially when that band overlaps with **radio-location**, **radio-navigation**, **maritime radio-navigation** and **satellite sensors**.

-Shea

**Comment by ps915** [comment]
agree =)

**Comment by darrindevine** [comment]
@asficas is the RX5808 capable of tuning the L-Band (5362 MHz to 5621 MHz) or did you use a different module?

**Comment by asficas** [comment]
The L-Band works fine on my TrueD diversity module and on a friends realacc diversity module, so my experience is that the RX5808 is capable of tuning the L-Band.

**Pull request merged**
