### PR TITLE
Multi diversity

### PR DESCRIPTION
**Pull request by rcdesigns**
Implemented Multi diversity, supporting up to 6 RX modules in OLED mode and 2 in TV Out mode.

### CODE REVIEW

**Comment by sheaivey** [comment]
Sorry for the delays... I'm working on the best way to merge your changes in without overwriting everything. Will probably wind up having two .ino projects.

**Comment by rcdesigns** [comment]
I wouldn't go out of your way pulling it in, unless you really want it that
is. I haven't seen anyone asking for it.

Steve

**Comment by Mercy404** [comment]
I would love to see this merged, I've been wanting to build an overkill monster ground station, and a 5 helical plus cloverleaf setup sounds perfect! Rebasing these changes on top of the current master is probably the easiest way to go about it.

**Comment by sheaivey** [comment]
Yes this branch is not completely compatible with the original project... I plan on closing this PR but i recommend anyone looking for multi-diversity to check out rcdesigns project.

https://github.com/rcdesigns/rx5808-pro-diversity/tree/MultiDiversity

**Comment by eamiralian** [comment]
That's a shame, I got 6 way diversity working, aside from some graphical glitches due to the number of receivers being displayed everything seems to work just fine.

**Comment by sheaivey** [comment]
Unfortunately along with the conflicts there is a lacking of documentation on the hardware changes necessary to build the multi diversity. Unless you can read the hardware changes from the code it is not as strait forward to build. 

My goal is to keep this project easy for everyone to build and that requires good documentation.

@eamiralian If you are willing to add that documentation and resolve the conflicts I'm happy to review the PR.

**Comment by jacobbloy** [comment]
@eamiralian

Do you have a quick photo of your setup or a schematic of how you got 6 way deversity working. My email is jacob.bloy@gmail.com,
This is for an event and I just need a hand and can pay a little bit!

**Comment by jacobbloy** [comment]
@rcdesigns

**Comment by eamiralian** [comment]
@jacobbloy Here's the diagram I used.
scanned_20170506-1829-page-001

**Comment by jacobbloy** [comment]
How did you get 6 to work I was looking at the 4051 which is a 8x switch

**Pull request closed without merging**
