### PR TITLE
Add support for boot logo/animations

### PR DESCRIPTION
**Pull request by Knifa**
This adds built-in support for custom boot animations, and can also be used to just show a single frame. This almost definitely conflicts with #97 (sorry!) and can do a little bit extra.

Number of frames, interval between frames, and number of repetitions are all configurable.

Example of included animation with 4 frames (happy to change): 
https://www.youtube.com/watch?v=sDgfKGVpHxE&feature=youtu.be

This uses a ton of memory as you would expect. 29,130 bytes (94%) with 4 frames vs 24,648 bytes (80%) without, with default configuration.

### CODE REVIEW

**Comment by sheaivey** [comment]
I'll probably hold off on merging this in until after your big clean up PR... https://github.com/sheaivey/rx5808-pro-diversity/pull/106

**Comment by Knifa** [comment]
No worries. I've managed to save a whole 2% of program space so far! :laugh:

**Comment by sheaivey** [comment]
If you are looking for a quick win on freeing up space you can replace all the display.width() and display.height() with defined values. This will allow the compiler to do the calculations and instead of

**Comment by Knifa** [comment]
Going to drop this in favour of the screensaver logo in #106.

**Pull request closed without merging**
