### PR TITLE
Adding a Start custom Logo

### PR DESCRIPTION
**Pull request by bbc25185**
I added the code that adds the possibility to insert your own logo in addition of the original from the Adafruit.

### CODE REVIEW

**Comment by kabturek** [comment]
Good stuff! how much program space does it need ?

**Comment by bbc25185** [comment]
Program space compiled without custom logo: 24564 bytes
Program space with custom logo: 25926 bytes

**Comment by kabturek** [comment]
thanks @bbc25185 , great it looks like i will have the space needed. will try :)

**Comment by sheaivey** [comment]
Please review the and fix any conflicts then I will merge in your changes.

**Comment by bbc25185** [comment]
Created a DOC for the creation of the LOGO...
Check my English please!!! im not good with it!!!

**Comment by sheaivey** [comment]
This is now built into release v2.0. See state_screensaver.cpp for implementation.

**Pull request closed without merging**
