### PR TITLE
Add option to dim display slightly on screensaver

### PR DESCRIPTION
**Pull request by Knifa**
Sorry for the PR spam.

This adds an option to dim the display when showing the screensaver (to save power, a tiny tiny bit). This might work better on some screens, it only changes a little on mine.

### CODE REVIEW

**Comment by sheaivey** [comment]
Fix conflicts and I'll get this one added in as well 😄

**Comment by Knifa** [comment]
Fixed!

**Comment by sheaivey** [comment]
Great! I'll try to be more active and up with your PRs as it seems like you have a lot of energy to improve things. If you have any questions feel free to reach out.

**Comment by Knifa** [comment]
Thanks, really appreciate it. I'm mostly just glad to be able to do something other than web development for a while!

**Pull request merged**
